version: '3.7'

services:
    postgres:
        image: postgres:9.6
        env_file: 
            - ./airflow.env
        environment:
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_USER=airflow
            - POSTGRES_DB=airflow
            # - POSTGRES_HOST=postgres
            #- POSTGRES_PORT=5432
            - PGDATA=/var/lib/postgresql/data/pgdata
            # - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
            - ./external_data:/var/lib/postgresql/data/external
        ports:
            - 5432:5432
#        expose:
#            - "5432"
        logging:
            options:
                max-size: 10m
                max-file: "3"
#        networks:
#            - nw_default

    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        env_file:
            - ./airflow.env
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_DB=airflow
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./tests:/usr/local/airflow/tests
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    api:
        # restart: always
        build: api
        environment:
          - POSTGRES_HOST_AUTH_METHOD=trust
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=5432
          - POSTGRES_DB=airflow
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
        ports:
            - 5000:5000
        depends_on:
            - postgres
        # command: python -m pip install --user flask && python app.py
#        networks:
#            - nw_default

#networks:
#    nw_default:
#        driver: bridge
        # external: true
